Repository debionetwork/debio-customer-ui, pull requests merged in 2021-12, with the labels that each got.

#163 ci: renamed testnet env
  .github/workflows/beta.yml
Labels: CI

#181 ci: update nginx conf
  nginx/conf.d/default.conf
Labels: CI

#184 ci: improve env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#189 ci: disable index.html cache
  nginx/conf.d/default.conf
Labels: CI

#192 ci: add kubernetes helm charts
  .maintain/kubernetes/.helmignore
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/hpa.yaml
  .maintain/kubernetes/templates/ingress.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/tests/test-connection.yaml
  .maintain/kubernetes/values.yaml
Labels: CI

#194 ci: improve nginx conf
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  nginx/conf.d/default.conf
Labels: CI

#198 Bugs create staking
  src/common/components/Dialog/index.vue
  src/common/lib/error-handler.js
  src/store/substrate/event-types.json
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: bug

#200 ci: add new env and fix mainnet secret
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#201 fix: update balance
  src/common/components/Navbar.vue
Labels: bug

#202 feat: TxWeight, update details page and update some EMR flow
  src/App.vue
  src/common/components/Modal/index.vue
  src/common/lib/polkadot-provider/command/electronic-medical-record.js
  src/router/routes/generateAccount.js
  src/router/routes/landing-page.js
  src/router/routes/signIn.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Details.vue
Labels: bug, enhancement, refactor

#210 ci: use gcr private repository
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#211 ci: fix image repository
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#212 ci: fix image tag
  .github/workflows/alpha.yml
  .github/workflows/release.yml
Labels: CI

#214 ci: enable autoscaling, Dockerfile modify
  .debio.pipeline.yml
  .dockerignore
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .maintain/docker/Dockerfile
  Dockerfile
  Dockerfile.demo
  build-demo.sh
  build-dev.sh
  build.sh
  docker-compose.yml
  reload-demo.sh
  reload-dev.sh
Labels: CI

#215 ci: improve high availability
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#216 ci: fix secret
  .github/workflows/release.yml
Labels: CI

#217 Ci cd
  .github/workflows/release.yml
Labels: CI
