Repository debionetwork/debio-customer-ui, pull requests merged in 2021-11, with the labels that each got.

#77 feat: fetch wallets
  src/common/components/Navbar.vue
Labels: enhancement

#75 update: change labs-api endpoint parameter to query
  src/common/lib/labs.js
  src/store/lab.js
  src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
Labels: enhancement

#68 feat: dropdown close on select and new search feature
  src/common/components/Dropdown/index.vue
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Details.vue
Labels: enhancement

#71 feat: test summary page
  src/common/icons/dna.js
  src/common/icons/familyTree.js
  src/common/icons/fileSearch.js
  src/common/icons/foodApple.js
  src/common/icons/hair.js
  src/common/icons/index.js
  src/common/icons/microscope.js
  src/common/icons/pill.js
  src/common/icons/qualityControlBanner.js
  src/common/icons/receivedBanner.js
  src/common/icons/registeredBanner.js
  src/common/icons/resultReadyBanner.js
  src/common/icons/virus.js
  src/common/icons/weightLifter.js
  src/common/icons/wetworkBanner.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/dataTesting.json
  src/views/Dashboard/Customer/Home/MyTest/index.vue
Labels: enhancement

#78 feat: add filter for verified labs
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
Labels: enhancement

#74 feat: enhance sign-in flow
  src/router/routes/signIn.js
  src/views/LandingPage/GenerateAccount/index.vue
  src/views/LandingPage/SignIn/ForgotPassword.vue
  src/views/LandingPage/SignIn/InputMnemonic.vue
  src/views/LandingPage/SignIn/index.vue
Labels: enhancement

#79 ci: fix Dockerfile
  .eslintrc.js
  Dockerfile
  package.json
Labels: ci/cd

#59 feat: Payment history integration
  src/common/components/Input/index.vue
  src/common/lib/metamask/mixins/metamaskServiceHandler.js
  src/common/lib/orders.js
  src/common/lib/polkadot-provider/query/orders.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/DataBounty/modalBounty.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/mock.json
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/RequestTestCheckout/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/Success/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/index.vue
Labels: enhancement

#73 Fix: Customer dashboard
  src/common/components/Banner/index.vue
  src/common/components/DataTable/index.vue
  src/common/icons/doctorDashboardIllustrator.js
  src/common/icons/index.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/MyTest/TestResult.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/index.vue
  src/views/Dashboard/Customer/index.vue
Labels: bug

#80 ci: connect to kubernetes cluster
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  .maintain/docker/Dockerfile
Labels: ci/cd

#83 fix: build.
  src/common/icons/index.js
Labels: bug

#81 fix: test status and validation
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: bug

#84 feat: implemented AES encryption.
  package-lock.json
  package.json
  src/common/lib/route-guard.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
Labels: enhancement

#86 ci: improve ci/cd - add draft release for alpha & beta
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: ci/cd

#88 fix: fix double quotes
  src/views/Dashboard/Customer/Home/Emr/Create.vue
Labels: bug

#91 fix: update terms & conditions and privacy policy links
  src/views/LandingPage/GenerateAccount/index.vue
Labels: bug

#97 fix: fix dai balance
  src/common/components/Navbar.vue
  src/common/components/WalletBinding.vue
  src/common/lib/metamask/wallet.js
Labels: bug, refactor

#98 feat: Add input password on mounted
  src/views/Dashboard/Customer/Layout.vue
Labels: enhancement

#92 refactor: update polkadot api instance
  package-lock.json
  src/store/substrate/index.js
  src/store/substrate/types.json
Labels: refactor

#103 ci: update Dockerfile
  Dockerfile
Labels: CI

#104 Update Dockerfile
  .maintain/docker/Dockerfile
Labels: CI

#87 fix: EMR bug and update details page
  src/common/components/Dropdown/index.vue
  src/common/components/Modal/index.vue
  src/common/components/Navbar.vue
  src/common/lib/ipfs/index.js
  src/common/lib/polkadot-provider/command/electronic-medical-record.js
  src/common/lib/polkadot-provider/query/electronic-medical-record.js
  src/common/lib/polkadot-provider/query/genetic-testing.js
  src/common/lib/polkadot-provider/query/orders.js
  src/common/lib/polkadot-provider/query/services.js
  src/common/lib/rating.js
  src/common/lib/utils/date.js
  src/common/lib/utils/index.js
  src/common/lib/utils/uuid.js
  src/common/lib/validate/validateInput.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Details.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
  src/views/Dashboard/Customer/Home/MyTest/TestResult.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: bug

#109 ci: fix vault env
  .github/workflows/main.yml
Labels: CI

#110 ci: fix create labs.js
  .github/workflows/main.yml
Labels: CI

#111 ci: cleaning unused code
  .github/workflows/main.yml
Labels: CI

#129 fix: close button in wallet binding
  src/common/components/Navbar.vue
  src/common/components/WalletBinding.vue
Labels: bug

#127 feat: enhance unstake request service
  src/common/components/Dialog/ConfirmationDialog.vue
  src/common/constants/staking-status.js
  src/common/lib/service-request.js
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/MyTest/stakingData.json
Labels: enhancement

#132 ci: improve deployment env secret
  .github/workflows/alpha.yml
Labels: CI

#137 ci: improve Dockerfile
  .maintain/docker/Dockerfile
Labels: CI

#130 fix: service detail mismatch
  src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: bug

#140 fix: bugs payment
  src/common/lib/metamask/escrow.js
  src/common/lib/polkadot-provider/command/orders.js
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
Labels: bug

#141 ci: fix refresh 404
  .maintain/docker/Dockerfile
  Dockerfile
  nginx/conf.d/default.conf
Labels: CI

#143 ci: separate staging environment
  .github/workflows/alpha.yml
Labels: CI

#125 fix: fix styling table on MyTest page
  src/common/components/NavigationDrawer.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
Labels: bug, enhancement
