Repository debionetwork/debio-customer-ui, pull requests merged in 2022-07, with the labels that each got.

#504 feat: adjust wording on generate acc
  src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue
Labels: fix

#505 fix: routes on notification
  src/store/substrate/event-types.json
Labels: fix

#507 fix: Event not show
  src/store/substrate/index.js
Labels: fix

#508 ci: improve github workflows
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: ci

#509 ci: update version & formatting
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/dev-tmp.yml
  .github/workflows/release.yml
  .github/workflows/tester.yml
  .github/workflows/update-version.yml
Labels: ci

#511 ci: fix create tags & release
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: ci

#512 fix: download file from pinata
  src/common/lib/pinata-proxy.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
Labels: fix

#514 ci: fix action permission
  .github/workflows/create-tags.yml
Labels: ci

#513 fix: get txhash on payment history
  package-lock.json
  package.json
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: fix

#517 ci: revert "fix action permission"
  .github/workflows/create-tags.yml
Labels: ci

#518 ci: revert "fix create tags & release"
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: ci

#520 ci: revert "improve github workflows"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: ci

#510 refactor: Remove genetic analyst folders
  src/common/lib/api/genetic-analyst/index.js
  src/common/lib/api/genetic-analyst/orders.js
  src/common/lib/api/index.js
  src/router/routes/geneticAnalyst.js
  src/router/routes/index.js
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Layout.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Card.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  src/views/Dashboard/GeneticAnalyst/Orders/index.vue
  src/views/Dashboard/GeneticAnalyst/Services/index.vue
  tests/unit/views/Dashboard/GeneticAnalyst/Account/index.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Home/index.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Orders/details.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/layout.spec.js
Labels: refactor

#521 feat: adjust button on payment detail - success
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: feature

#515 fix: payment-detail-card
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: fix

#516 feat: display app version
  package.json
  src/common/components/NavigationDrawer.vue
Labels: feature, improvement

#522 ci: added app version
  .env-example
  .github/workflows/builder.yml
Labels: ci

#524 ci: get package version
  .github/workflows/builder.yml
Labels: ci

#525 chore: bump version to 2.1.5
  package.json
Labels: feature

#526 fix: package.json
  package-lock.json
  package.json
Labels: fix

#528 fix: switch network
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: fix

#527 feat: update phrase on stake service page and agreement pop up
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
Labels: feature

#529 refactor: update EMR to PHR
  src/common/lib/api/customer/index.js
  src/common/lib/api/customer/phr.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/Phr/Create.vue
  src/views/Dashboard/Customer/Home/Phr/Details.vue
  src/views/Dashboard/Customer/Home/Phr/Edit.vue
  src/views/Dashboard/Customer/Home/Phr/index.vue
  src/views/Dashboard/Customer/Home/index.vue
  src/views/Dashboard/Customer/Layout.vue
  tests/unit/views/Dashboard/Customer/Home/Phr/create.spec.js
  tests/unit/views/Dashboard/Customer/Home/Phr/details.spec.js
  tests/unit/views/Dashboard/Customer/Home/Phr/edit.spec.js
  tests/unit/views/Dashboard/Customer/Home/Phr/index.spec.js
Labels: refactor

#532 feat: direct data bounty to maintenance page
  src/views/Dashboard/Customer/Layout.vue
  src/views/Dashboard/maintenancePageLayout.vue
Labels: fix

#533 feat: adjust empty genetic data page to figma
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/EmptyDataCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue
Labels: improvement

#534 fix: error on connect to metamask on payment
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: fix

#536 feat: add converter usd on payment card
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: fix

#537 feat: enhance req test - staking flow
  src/store/lab.js
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
Labels: feature
