Repository debionetwork/debio-customer-ui, pull requests merged in 2022-02, with the labels that each got.

#286 Create code analyzer
  .github/workflows/analyzer.yml
Labels: ci

#283 [DBIO-1650] fix: adjust emr edit & add tx weight
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
Labels: fix

#268 [DBIO-1469] Tests: Unit testing fle component
  tests/unit/common/components/file.spec.js
Labels: tests

#271 [DBIO-1474] Tests: unit testing input component
  tests/unit/common/components/input.spec.js
Labels: tests

#275 [DBIO-1581] tests: unit test checkout page
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/Checkout/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/Checkout/payment-checkout.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/lab-detail-card.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/pay-remaining-dialog.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-detail-card.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-receipt-dialog.spec.js
Labels: tests

#279 [DBIO-1579] tests: test select location
  tests/unit/views/Dashboard/Customer/Home/RequestTest/request-test-form.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/select-location.spec.js
Labels: tests

#288 [DBIO-1776] fix: adjust layout unlock wallet
  src/views/Dashboard/Customer/Layout.vue
Labels: fix

#289 [DBIO-1777] fix: TxWeight number toFixed 4
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
Labels: fix, improvement

#291 [DBIO-1781] ci: add nodeSelector to deployment
  .github/workflows/deployer.yml
  .github/workflows/dev-tmp.yml
Labels: ci

#285 [DBIO-1747, DBIO-1705, DBIO-1748] feat: add genetic data analysis pages
  src/assets/check-circle-primary.png
  src/common/components/Dialog/SuccessDialog.vue
  src/common/components/NavigationDrawer.vue
  src/common/constants/error-messages.js
  src/common/constants/rules.js
  src/common/icons/geneticDna.js
  src/common/icons/geneticIllustration.js
  src/common/icons/index.js
  src/common/icons/plus-circle.js
  src/common/lib/polkadot-provider/command/genetic-data.js
  src/common/lib/polkadot-provider/query/genetic-data.js
  src/router/routes/index.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis.vue
  src/views/Dashboard/Customer/Home/GeneticData/index.vue
  src/views/Dashboard/Customer/Home/MyTest/ConfirmationDialog.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#284 [DBIO-1732] feat: Add a new Genetic Analyst dashboard
  src/common/components/Avatar/index.vue
  src/common/components/Breadcrumbs/index.vue
  src/common/components/File/index.vue
  src/common/components/Navbar.vue
  src/common/components/Stepper/index.vue
  src/common/icons/chevronLeft.js
  src/common/icons/geneticAnalystIllustration.js
  src/common/icons/index.js
  src/common/icons/timer.js
  src/router/routes/customer.js
  src/router/routes/geneticAnalyst.js
  src/router/routes/index.js
  src/router/routes/signIn.js
  src/views/Dashboard/Customer/Layout.vue
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Layout.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Card.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  src/views/Dashboard/GeneticAnalyst/Orders/index.vue
  src/views/Dashboard/GeneticAnalyst/Services/index.vue
  src/views/Dashboard/maintenancePageLayout.vue
  src/views/LandingPage/SelectRole/RoleButton.vue
  src/views/LandingPage/SelectRole/index.vue
  src/views/LandingPage/SignIn/index.vue
  tests/unit/views/LandingPage/SelectRole/role-button.spec.js
Labels: feature

#293 [DBIO-1466] test: Unit Testing DataTable components
  tests/unit/common/components/dataTable/data-table.spec.js
Labels: tests

#295 fix: Redirect page
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/SelectRole/index.vue
Labels: fix

#299 [DBIO-1613] tests: payment history
  tests/unit/views/Dashboard/Customer/Home/PaymentHistory/index.spec.js
Labels: tests

#298 [DBIO-1774] fix: handle events index condition
  src/common/lib/polkadot-provider/events/index.js
  src/store/substrate/event-types.json
Labels: fix

#287 [DBIO-1749] feat: Add genetic analysis list tab
  src/common/icons/trash.js
  src/common/styles/functions.sass
  src/views/Dashboard/Customer/Home/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#274 [DBIO-1326] Style: styling page myTest
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
Labels: fix

#301 [DBIO-1644] tests: mock ipfs lib.
  jest.config.js
  tests/unit/crypt-worker.mock.js
  tests/unit/ipfs-index.mock.js
  tests/unit/ipfs-worker.mock.js
  tests/unit/worker.mock.js
Labels: tests

#303 [DBIO-1712, DBIO-1743, DBIO-1744, DBIO-1797] feat : Enhance Request Analysis Flow
  src/assets/linkedin-logo.png
  src/common/components/DataTable/index.vue
  src/common/constants/rules.js
  src/common/icons/emptyDataIllustration.js
  src/common/icons/index.js
  src/common/lib/api/debio-balance.js
  src/common/lib/polkadot-provider/command/genetic-analysis-orders.js
  src/common/lib/polkadot-provider/query/genetic-analysis-orders.js
  src/common/lib/polkadot-provider/query/genetic-analysis.js
  src/common/lib/polkadot-provider/query/genetic-analyst-qualifications.js
  src/common/lib/polkadot-provider/query/genetic-analyst-service.js
  src/common/lib/polkadot-provider/query/genetic-analysts.js
  src/common/lib/polkadot-provider/query/genetic-data.js
  src/router/routes/customer.js
  src/store/genetic-data.js
  src/store/index.js
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/CheckoutPayment.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/Information.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/NoDataCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/pay-remaining-dialog.spec.js
Labels: feature

#294 [DBIO-1176] fix: adjust popup unlock wallet
  src/views/Dashboard/Customer/Layout.vue
Labels: fix

#307 [DBIO-766] Chore: update CID biological sample collection process
  src/common/constants/instruction-step.js
Labels: refactor

#304 [DBIO-1774] fix: notification unstake
  src/common/lib/polkadot-provider/events/index.js
Labels: fix

#306 [DBIO-1833] feat : Refactor code and update GA wiring
  src/common/components/Textarea/index.vue
  src/common/lib/api/customer/categories.js
  src/common/lib/api/customer/debio-balance.js
  src/common/lib/api/customer/emr.js
  src/common/lib/api/customer/gcs.js
  src/common/lib/api/customer/index.js
  src/common/lib/api/customer/labs.js
  src/common/lib/api/customer/location.js
  src/common/lib/api/customer/orders.js
  src/common/lib/api/customer/rating.js
  src/common/lib/api/customer/service-request.js
  src/common/lib/api/genetic-analyst/index.js
  src/common/lib/api/genetic-analyst/orders.js
  src/common/lib/api/index.js
  src/common/lib/polkadot-provider/command/genetic-analyst/orders.js
  src/common/lib/polkadot-provider/query/genetic-analyst/analysis.js
  src/common/lib/polkadot-provider/query/genetic-analyst/analyst.js
  src/common/lib/polkadot-provider/query/genetic-analyst/geneticData.js
  src/common/lib/polkadot-provider/query/genetic-analyst/orders.js
  src/common/lib/polkadot-provider/query/genetic-analyst/services.js
  src/store/substrate/index.js
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix, feature, refactor, improvement

#300 [DBIO-1831] Feat: Genetic Analysis list tab
  src/common/lib/polkadot-provider/query/genetic-analysis.js
  src/common/lib/polkadot-provider/query/genetic-analysts.js
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Home/GeneticData/index.vue
Labels: feature, refactor

#308 [DBIO-1643] test: unit testing customer EMR details
  tests/unit/views/Dashboard/Customer/Home/Emr/Details.spec.js
Labels: tests

#305 [DBIO-1330] feat: post tx hash to database
  src/common/lib/api/index.js
  src/common/lib/api/tx-hash.js
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: feature

#311 Fix: error in genetic analysis & genetic analysts
  src/common/lib/polkadot-provider/query/genetic-analysis.js
  src/common/lib/polkadot-provider/query/genetic-analysts.js
Labels: fix

#309 [DBIO-1743, DBIO-1744, DBIO-1797 ] feat: add reject page and fix some bugs
  src/common/lib/api/customer/genetic-analysis-order.js
  src/common/lib/api/customer/index.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/EmptyDataCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue
Labels: fix, feature

#314 [DBIO-1871] fix: Some issue with description and update layout
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
  src/views/Dashboard/Customer/Layout.vue
  src/views/Dashboard/GeneticAnalyst/Layout.vue
Labels: fix, improvement

#316 [DBIO-1868, DBIO-1867] fix: add loading experience & empty data views
  src/assets/no-data-list.svg
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
Labels: fix, feature

#315 [DBIO-1574] Tests: unit testing customer DashBoard
  tests/unit/views/Dashboard/Customer/Home/home.spec.js
Labels: tests

#317 fix: Several issues
  src/assets/defaultAvatar.svg
  src/assets/defaultImage.svg
  src/common/components/Avatar/index.vue
  src/router/routes/signIn.js
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/SignIn/index.vue
Labels: fix, improvement

#319 [DBIO-1876] Fix: change genetic analysis order API
  src/common/lib/api/customer/genetic-analysis-order.js
Labels: fix

#320 [DBIO-1743] fix: change debio logo to defaultAvatar
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/EmptyDataCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
Labels: fix

#322 [DBIO-1872] feat: websocket connection watcher.
  src/App.vue
  src/common/lib/polkadot-provider/index.js
  src/common/lib/polkadot-provider/util.js
  src/store/substrate/index.js
Labels: feature, improvement

#321 [DBIO-1876] Fix: Api genetic analysis order
  src/common/lib/api/customer/genetic-analysis-order.js
  src/common/lib/api/index.js
Labels: fix

#312 [DBIO-1323] feat: Add button view to etherscan
  src/common/lib/api/orders.js
  src/common/styles/function.sass
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  tests/unit/views/Dashboard/Customer/Home/home.spec.js
Labels: feature, improvement

#324 refactor: Remove button on step 3 and update validation
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: refactor, improvement

#328 [DBIO-1831] Fix: Ceate Genetic Analysis lists Tab
  src/common/lib/api/customer/genetic-analysis-order.js
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
Labels: fix

#327 [DBIO-1739] fix: Several issue
  src/App.vue
  src/common/constants/rules.js
  src/common/icons/cableError.js
  src/common/icons/index.js
  src/common/lib/validate/validateForms.js
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix, improvement

#326 [DBIO-1874] feat : Announcement
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#325 [DBIO-1866] fix: fix styling on success upload pop up
  src/common/components/Dialog/SuccessDialog.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
Labels: fix

#329 [DBIO-1879] feat: add sort for genetic analysis list table.
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
Labels: fix

#331 [DBIO-1756] tests: genetic analysis list page.
  tests/unit/views/Dashboard/Customer/Home/GeneticData/genetic-analysis-list.spec.js
  tests/unit/views/Dashboard/Customer/Home/genetic-analyst-list.spec.js
Labels: test

#330 [DBIO-1736, DBIO-1740] tests: genetic analyst orders detail.
  tests/unit/views/Dashboard/Customer/Home/Emr/create.spec.js
  tests/unit/views/Dashboard/Customer/Home/Emr/details.spec.js
  tests/unit/views/Dashboard/Customer/Home/Emr/edit.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Orders/details.spec.js
  tests/unit/views/LandingPage/SelectRole/index.spec.js
Labels: test

#332 [DBIO-1754] tests: genetic data list page.
  tests/unit/views/Dashboard/Customer/Home/GeneticData/genetic-data-list.spec.js
Labels: test

#335 [DBIO-1739] fix: Minor fix button disabled and update placeholder wording
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix, improvement

#336 [DBIO-1733] tests: genetic analyst dashboard unit tests.
  tests/unit/views/Dashboard/GeneticAnalyst/Account/index.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Home/index.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/layout.spec.js
Labels: test

#339 fix: GA Dynamic order accepted
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix, improvement

#333 [DBIO-1831] Fix: order status GA step 4
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: fix

#344 [DBIO-1831] Chore: enhance genetic analysis tab list
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
Labels: fix, improvement

#343 fix: Add button loading and code improvement
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix, improvement

#346 [DBIO-1885] fix: update variable profile image not loaded
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
Labels: fix

#338 [DBIO-1705] feat: pinata ipfs upload
  package-lock.json
  package.json
  src/common/components/Dialog/SuccessDialog.vue
  src/common/components/Dialog/UploadingDialog.vue
  src/common/lib/ipfs/crypt-worker/encrypt-worker-file.js
  src/common/lib/pinata/index.js
  src/common/lib/polkadot-provider/command/genetic-analysis-orders.js
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: feature

#347 [DBIO-1705] feat: implement debionetwork-pinata-ipfs
  src/common/lib/pinata/index.js
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: refactor

#348 Add New ENV
  .github/workflows/builder.yml
Labels: ci

#345 [DBIO-1892] refactor: Update ipfs with pinata
  src/common/lib/pinata/index.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Details.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: refactor, improvement

#350 fix: IPFS error upload and remove trailing spaces
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: fix

#351 ci: change deployment env
  .github/workflows/builder.yml
Labels: ci

#352 add AGPL-3.0 licence
  LICENSE
Labels: document
