Repository debionetwork/debio-customer-ui, pull requests merged in 2022-10, with the labels that each got.

#595 fix: today summary
  src/common/constants/menstruation-moods.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
Labels: fix

#596 emojies and update menstrual calendar
  src/assets/emoji-happy-active.svg
  src/assets/emoji-happy-inactive.svg
  src/common/components/Day.vue
  src/common/constants/menstrual-symptoms-emoji.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: feature

#598 feat: staking validation
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
Labels: feature

#597 feat: Emoji calendar
  src/common/components/Calendar.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: improvement

#599 feat: enhance genetic analysis payment
  src/common/components/Navbar.vue
  src/common/lib/polkadot-provider/command/geneticAnalysisOrders.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
Labels: feature

#591 feat: enhance staking request test payment
  src/common/lib/polkadot-provider/command/order.js
  src/common/lib/polkadot-provider/query/service-request.js
  src/common/lib/price-format.js
  src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
  src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
  src/views/Dashboard/Customer/Home/RequestTest/PayRemainingDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/pay-remaining-dialog.spec.js
Labels: feature

#612 ci: improvements
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/1.bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/cicd.yaml
  .github/workflows/cii.yaml
  .github/workflows/deployer.yaml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/releaser.yaml
  .github/workflows/sast.yaml
  .github/workflows/tester.yaml
  .maintain/docker/Dockerfile
  .maintain/docker/entrypoint.sh
  .maintain/install-hooks.sh
  CODEOWNERS
  README.md
  package.json
Labels: ci

#600 feat: connect menstrual calendar selection to substrate
  src/common/components/Day.vue
  src/common/components/DaySelectAverage.vue
  src/common/lib/polkadot-provider/command/menstrual-calendar.js
  src/common/lib/polkadot-provider/query/menstrual-calendar.js
  src/store/menstrual-calendar.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: feature

#611 add region and country name for selected service
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
Labels: improvement

#630 feat: remove-metamask
  src/App.vue
  src/common/components/Dialog/InstallMetamask.vue
  src/common/components/Navbar.vue
  src/common/lib/api/customer/index.js
  src/common/lib/api/customer/tx-hash.js
  src/common/lib/api/customer/wallet.js
  src/common/lib/metamask/escrow.js
  src/common/lib/metamask/index.js
  src/common/lib/metamask/mixins/README.md
  src/common/lib/metamask/mixins/metamaskServiceHandler.js
  src/common/lib/metamask/usdt/abi.json
  src/common/lib/metamask/usdt/index.js
  src/common/lib/metamask/wallet.js
  src/main.js
  src/store/ethereum/index.js
  src/store/index.js
  src/store/metamask/contracts/abi/ERC20Interface.json
  src/store/metamask/contracts/abi/Escrow.json
  src/store/metamask/contracts/index.js
  src/store/metamask/index.js
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/Phr/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#629 fix: link to lab service request page
  src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
Labels: fix, bug

#631 fix: format usdt on payment history detail
  src/common/components/Navbar.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: fix

#633 fix: usdn
  src/common/components/Navbar.vue
  src/common/lib/polkadot-provider/query/octopus-assets.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: feature

#621 fix: update menstrual cycle log and average
  src/common/lib/polkadot-provider/command/menstrual-calendar.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: fix

#634 feat: wiring menstrual subscription and payment to substrate
  src/common/lib/polkadot-provider/command/menstrual-subscription.js
  src/common/lib/polkadot-provider/query/menstrual-subscription.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: feature

#640 fix: read env daomaps link
  src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
Labels: fix

#641 fix: proceed button & insufficient balance error
  src/common/lib/polkadot-provider/command/service-request.js
  src/common/lib/polkadot-provider/query/service-request.js
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: fix

#645 fix: show success dialog
  src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
Labels: fix
