Repository debionetwork/debio-customer-ui, pull requests merged in 2022-12, with the labels that each got.

#694 fix: insufficient balance for menstrual subscription
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: fix

#695 feat: add countdown subscription in calendar
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
Labels: feature

#696 chore(main): release 2.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#697 fix: coming soon label menstrual calendar landing page
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: fix, improvement

#705 fix: query price menstrual subscription
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: fix

#708 feat: export keystore
  src/common/components/Navbar.vue
Labels: feature

#707 fix: USDTE on Payment Details page
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: fix

#712 fix: remove toUpperCase on menu card
  src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
Labels: fix

#709 feat: add second opinion and fix bugs
  src/assets/second-opinion-banner.svg
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/Banner.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: fix, feature

#718 fix: payment when no octopusAsset
  src/common/components/Navbar.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: fix

#715 fix: staking tab
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
Labels: fix

#714 feat: add pop up install polkadot extension
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/Description.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/GrantAccessPHR.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/index.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
Labels: feature

#713 fix: typos on summary component
  src/common/components/Navbar.vue
  src/common/constants/menstruation-moods.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
Labels: fix

#699 chore(main): release 2.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#724 fix: reassign assetId
  src/common/components/Navbar.vue
Labels: fix

#723 fix: adjust queryGeneticAnalysisOrderById from polkadot lib in FE to polkadot-provider
  src/common/lib/polkadot-provider/query/genetic-analysis-orders.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
Labels: fix

#726 feat: adjust some wording and add dummy data
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/Banner.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/dummyRequestedOpinionList.json
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
Labels: feature

#729 feat: adjust new wording on install polkadot pop up
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
Labels: feature

#732 fix: install polkadot width
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
Labels: fix

#734 feat: add connect page in customer
  src/assets/debio-to-myriad.svg
  src/assets/myriad-logo.png
  src/router/index.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/GrantAccessPHR.vue
Labels: feature
