Repository debionetwork/debio-customer-ui, pull requests merged in 2022-03, with the labels that each got.

#354 [DBIO-1836] Fix: fix some wording
  src/views/Dashboard/Customer/Home/index.vue
Labels: fix

#353 fix: Array geneticLink download
  src/common/lib/pinata/index.js
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix, improvement

#356 fix: IPFS download file type
  src/common/lib/pinata/index.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Details.vue
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix, improvement

#357 [DBIO-1873] Fix: Change wording checkout payment GA loading dialog
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/CheckoutPayment.vue
Labels: fix

#359 fix: Data response from downloading file
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: fix, improvement

#360 [DBIO-1705] fix: fix get file when edit
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
Labels: fix

#362 [DBIO-1705] fix: fix file type
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: fix

#363 fix: fix downloading file in ga
  src/common/lib/pinata/index.js
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix

#364 fix: minor update filename
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: fix, improvement

#365 fix : Pinata improvement feature
  src/common/lib/pinata/index.js
Labels: fix, improvement

#366 fix: File naming when re-upload file
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: fix

#370 [DBIO-1798, DBIO-1713, DBIO-1746] tests: add unit test step 4 request analysis
  src/router/routes/customer.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/empty-data.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/information.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/select-service-analysis.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/success-page.spec.js
  tests/unit/views/Dashboard/Customer/Home/index.spec.js
Labels: test

#373 [DBIO-1810] feat: add staking id to staking service tab
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: fix

#368 [DBIO-1745] test: unit testing req GA step 3
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/checkout-payment.spec.js
Labels: test

#374 fix: recaptcha sitekey.
  src/views/LandingPage/GenerateAccount/SetPassword.vue
Labels: fix

#372 [DBIO-2002] fix: Css bug and remove trailing spaces
  src/common/components/NavigationDrawer.vue
  src/views/LandingPage/GenerateAccount/GenerateMnemonic/MnemonicList.vue
  src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/GenerateAccount/VerifyMnemonic/MnemonicInput/MnemonicKeypad.vue
  src/views/LandingPage/GenerateAccount/VerifyMnemonic/MnemonicInput/index.vue
  src/views/LandingPage/GenerateAccount/index.vue
  src/views/LandingPage/LandingPagePopUp.vue
  src/views/LandingPage/Layout.vue
  src/views/LandingPage/SignIn/ChangePasswordSuccessful.vue
  src/views/LandingPage/SignIn/ForgotPassword.vue
  src/views/LandingPage/SignIn/index.vue
  src/views/LandingPage/index.vue
Labels: fix, refactor

#376 cd: fix limit-rps error
  .github/workflows/deployer.yml
Labels: ci

#377 fix: recaptcha.
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: fix

#379 [DBIO-1669] fix: enhance wording on generate account according to figma
  package-lock.json
  package.json
  src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/GenerateAccount/VerifyMnemonic/index.vue
  src/views/LandingPage/GenerateAccount/index.vue
Labels: fix, improvement

#381 [DBIO-1811] fix: EMR several issues
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
Labels: fix, improvement

#378 merge main-tmp to main
  src/common/lib/api/customer/orders.js
  src/common/lib/api/tx-hash.js
  src/common/styles/function.sass
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  tests/unit/common/components/dataTable/data-table.spec.js
  tests/unit/views/Dashboard/Customer/Home/PaymentHistory/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/home.spec.js
Labels: feature

#382 [DBIO-1668] fix: adjust validation message with sheet
  src/common/constants/error-messages.js
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/LandingPage/GenerateAccount/VerifyMnemonic/index.vue
  src/views/LandingPage/SignIn/InputMnemonic.vue
  src/views/LandingPage/SignIn/index.vue
  tests/unit/common/components/dataTable/data-table.spec.js
  tests/unit/views/Dashboard/Customer/Home/home.spec.js
Labels: fix, improvement

#384 [DBIO-2088] feat: create logic for unavailable city on request test
  src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
Labels: fix, improvement

#383 [DBIO-1909] fix: create default sortir table on genetic data list
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue
Labels: improvement

#385 [DBIO-1966] feat: add progress uploading in axios and implement to add genetic data
  src/common/components/Dialog/UploadingDialog.vue
  src/common/lib/pinata/index.js
  src/store/genetic-data.js
Labels: improvement

#375 [DBIO-1799] feat: create DSC sortir table list on "stake service" and "request test"
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
Labels: fix

#386 [DBIO-2096] fix: fix some error, tx weights and insufficient pop up
  src/common/lib/api/customer/index.js
  src/common/lib/api/customer/tx-hash.js
  src/common/lib/polkadot-provider/command/info.js
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/RequestTest/PayRemainingDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  tests/unit/views/Dashboard/Customer/Home/GeneticData/genetic-data-list.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-receipt-dialog.spec.js
Labels: fix, improvement

#380 [DBIO-1790] feat: Add staking hash ID to notification wording
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/common/lib/polkadot-provider/events/index.js
  src/store/substrate/event-types.json
Labels: improvement

#387 tests: homepage integration tests using cypress
  .eslintrc.js
  cypress.json
  package-lock.json
  package.json
  tests/e2e/.gitignore
  tests/e2e/plugins/index.js
  tests/e2e/specs/homepage.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/index.js
  tests/unit/crypt-worker.mock.js
  tests/unit/ipfs-worker.mock.js
  tests/unit/views/Dashboard/Customer/Home/Emr/create.spec.js
  tests/unit/views/Dashboard/Customer/Home/Emr/edit.spec.js
  tests/unit/views/Dashboard/Customer/Home/Emr/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/checkout-payment.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/empty-data.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/information.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/select-service-analysis.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/success-page.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/add.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/genetic-analysis-list.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/genetic-data-list.spec.js
  tests/unit/views/Dashboard/Customer/Home/genetic-analyst-list.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Home/index.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Orders/details.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/layout.spec.js
Labels: test

#388 ci: optimize deployment resource request & limit
  .github/workflows/deployer.yml
Labels: ci

#389 [DBIO-1669, DBIO-2097] fix: fix wording on generate account & add genetic data
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue
Labels: fix

#392 [DBIO-2090] feat: update wording for important information pop up
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/Information.vue
Labels: feature, improvement

#391 [DBIO-2089] feat: update description in payment card
  src/common/styles/mixins.sass
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: feature, improvement

#394 feat: git hooks
  .maintain/install-hooks.sh
  package.json
Labels: feature, ci, test

#390 [DBIO-1612] feat: handle general error
  src/common/lib/api/index.js
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#396 [DBIO-1811] refactor: EMR txWeight
  src/views/Dashboard/Customer/Home/Emr/Create.vue
Labels: refactor, improvement

#395 fix: View on etherscan
  src/common/lib/api/customer/orders.js
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: fix

#397 feat: Update payment history with GA orders
  src/common/lib/api/customer/orders.js
  src/common/lib/api/index.js
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
Labels: feature, improvement

#399 fix: EMR uploading
  src/views/Dashboard/Customer/Home/Emr/Create.vue
Labels: fix

#400 [DBIO-2198, DBIO-2199] feat: create ga order details page
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/GeneticData/Details/ReasonOfRejection.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/ServiceCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/reason-of-rejection.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/service-card.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/stepper-status-card.spec.js
Labels: feature

#401 [DBIO-2104, DBIO-1908] fix: fix blocker in sonar cloud
  package-lock.json
  package.json
  src/common/components/Navbar.vue
  src/common/lib/metamask/index.js
  src/common/lib/polkadot-provider/command/orders.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Details.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/LandingPage/GenerateAccount/GenerateMnemonic/MnemonicList.vue
  src/views/LandingPage/GenerateAccount/VerifyMnemonic/MnemonicInput/MnemonicKeypad.vue
  src/views/LandingPage/GenerateAccount/VerifyMnemonic/MnemonicInput/index.vue
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/reason-of-rejection.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/service-card.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/stepper-status-card.spec.js
Labels: fix

#403 fix: fix debio balance in navbar
  package-lock.json
  src/common/components/Navbar.vue
Labels: fix
