Repository debionetwork/debio-customer-ui, pull requests merged in 2022-05, with the labels that each got.

#446 fix: EMR several issues
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
Labels: fix, improvement

#444 fix: Payment history several issues
  src/views/Dashboard/Customer/Home/MyTest/TestResult.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
Labels: fix, improvement

#449 fix: GA test result decryption
  src/views/Dashboard/Customer/Home/GeneticData/Result.vue
Labels: fix

#450 fix: fix download ga result
  src/common/lib/pinata-proxy.js
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
Labels: fix

#441 fix: Minor update wording notification
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/store/substrate/event-types.json
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  tests/unit/views/Dashboard/Customer/Home/PaymentHistory/details.spec.js
Labels: fix, improvement

#443 fix: detail button on dashboard - recent test
  src/views/Dashboard/Customer/Home/index.vue
Labels: fix

#445 fix: Order detail blank page
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/index.vue
Labels: fix, improvement

#447 tests: Add unit testing test result page
  tests/unit/views/Dashboard/Customer/Home/MyTest/test-result.spec.js
Labels: test

#451 fix : Enhance request test
  src/store/test-request.js
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/Success/PaymentSuccess.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/Success/payment-success.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/lab-detail-card.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-detail-card.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-receipt-dialog.spec.js
Labels: fix, test, refactor

#452 fix: styling on pop up
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/MyTest/ConfirmationDialog.vue
Labels: fix

#453 fix: wording on password validation
  src/views/LandingPage/GenerateAccount/SetPassword.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: fix

#454 fix: Etherscan redirect
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: fix

#455 fix: Refunded amount value
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: fix

#457 ci: add new env
  .github/workflows/builder.yml
Labels: ci
