Repository debionetwork/debio-customer-ui, pull requests merged in 2022-04, with the labels that each got.

#404 [DBIO-2241] fix: styling on showing anlysis service (step 2)
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
Labels: fix

#407 [DBIO-1783] fix: adjust parameter on createOrder
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: fix, refactor

#408 feat: update polkadot provider package
  package-lock.json
  package.json
  src/common/lib/polkadot-provider/command/genetic-analysis-orders.js
  src/common/lib/polkadot-provider/command/genetic-analyst/orders.js
  src/common/lib/polkadot-provider/command/orders.js
  src/common/lib/polkadot-provider/command/service-request.js
  src/common/lib/polkadot-provider/query/genetic-analysis-orders.js
  src/common/lib/polkadot-provider/query/genetic-analysis.js
  src/common/lib/polkadot-provider/query/genetic-analyst-qualifications.js
  src/common/lib/polkadot-provider/query/genetic-analyst-service.js
  src/common/lib/polkadot-provider/query/genetic-analyst/services.js
  src/common/lib/polkadot-provider/query/genetic-analysts.js
  src/common/lib/polkadot-provider/query/genetic-testing.js
  src/views/Dashboard/Customer/Home/GeneticData/Details/ReasonOfRejection.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/ServiceCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
  src/views/Dashboard/Customer/Home/MyTest/TestResult.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
  src/views/Dashboard/Customer/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/agreement-dialog.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/no-lab.spec.js
  tests/unit/views/Dashboard/Customer/Home/home.spec.js
  tests/unit/views/Dashboard/Customer/Home/index.spec.js
Labels: feature, test

#409 fix: error genetic data list
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue
Labels: fix

#310 [DBIO-1401] Fix: service image mismatch
  src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: fix

#410 fix: EMR document lists
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/Emr/deprecated/Confirm.vue
  src/views/Dashboard/Customer/Home/Emr/deprecated/Create.vue
  src/views/Dashboard/Customer/Home/Emr/deprecated/Upload.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
Labels: fix

#412 fix: fix signout and upgrade polkadot-package version to 0.0.9
  package-lock.json
  package.json
  src/common/components/Navbar.vue
Labels: fix

#411 fix: fix success pop up after edit genetic data
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
Labels: fix

#413 fix: download result sample & staking amount
  src/common/lib/polkadot-provider/command/service-request.js
  src/common/lib/polkadot-provider/query/genetic-analysts-services.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
Labels: fix

#414 ci: add new env
  .github/workflows/builder.yml
  .github/workflows/dev-tmp.yml
Labels: ci

#416 fix: fix rename function tx weight on customer-ui
  src/common/lib/polkadot-provider/query/genetic-analysis-orders.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/CheckoutPayment.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: fix, refactor

#406 feat: Genetic order detail page
  src/common/lib/pinata-proxy.js
  src/common/plugins/vuetify.js
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  tests/unit/views/Dashboard/Customer/Home/PaymentHistory/details.spec.js
Labels: feature, test, improvement

#415 fix: Mismatch order notification
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/store/substrate/event-types.json
Labels: fix

#421 fix: request analysis payment flow
  package-lock.json
  package.json
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/ReasonOfRejection.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: fix, improvement

#419 fix: enhance customer notification
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/store/substrate/event-types.json
Labels: fix

#423 fix: fix bugs add genetic data
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
Labels: fix

#426 fix: genetic analysis list tabel
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
Labels: fix

#428 fix: fix details genetic analysis
  src/views/Dashboard/Customer/Home/GeneticData/Details/ReasonOfRejection.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
Labels: fix

#429 fix: Payment history Refunded value
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: fix

#433 fix: checkout ga order & empty genetic data page
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue
Labels: fix, refactor

#432 fix: fix status general error from api
  src/common/lib/api/index.js
Labels: fix

#434 fix: error on payment ga card
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
Labels: fix, refactor

#431 fix: fetch dashboard and my test
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/index.vue
Labels: fix, refactor

#437 fix: button validation on add genetic data
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
Labels: fix

#435 feat: Init view result analysis page
  src/common/components/Navbar.vue
  src/router/routes/customer.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Result.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
  src/views/Dashboard/Customer/Home/index.vue
  tests/unit/views/Dashboard/Customer/Home/GeneticData/result.spec.js
Labels: feature

#439 fix: minor update layout
  src/views/Dashboard/Customer/Home/MyTest/TestResult.vue
Labels: fix, improvement

#436 fix: wording and format price on rejected order details
  src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
Labels: fix

#438 fix: download test result sample
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: fix
