Repository debionetwork/debio-customer-ui, pull requests merged in 2022-09, with the labels that each got.

#557 feat: apply unlimited description and purchase link available field
  src/common/styles/mixins.sass
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/CheckoutPayment.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/RequestTest/Canceled/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/Success/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/index.vue
Labels: feature

#558 feat: remove required field
  .maintain/Dockerfile
  src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
Labels: improvement

#556 feat: enhance notification
  src/common/components/Navbar.vue
  src/common/lib/api/customer/index.js
  src/common/lib/api/customer/notifications.js
  src/common/lib/notification.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#561 fix: request a service link
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
Labels: fix

#560 feat: add sidebar for menstrual calendar
  src/common/components/NavigationDrawer.vue
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#562 feat: runtime env variable
  .dockerignore
  .env-template
  .maintain/Dockerfile
  .maintain/docker/Dockerfile
  .maintain/docker/entrypoint.sh
  .maintain/docker/nginx/conf.d/default.conf
  .maintain/docker/nginx/nginx.conf
  docs/metamask-wallet-creation-steps.md
  docs/test-wallet.md
  public/index.html
  src/common/components/NavigationDrawer.vue
  src/common/lib/api/index.js
  src/common/lib/metamask/escrow.js
  src/common/lib/metamask/wallet.js
  src/common/lib/pinata-proxy.js
  src/common/lib/utils/env.js
  src/main.js
  src/router/index.js
  src/store/auth.js
  src/store/metamask/contracts/index.js
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/LandingPage/GenerateAccount/SetPassword.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: feature

#563 fix: bugs on store.connect
  src/common/lib/utils/env.js
  src/store/substrate/index.js
Labels: fix, bug

#564 ci: move registry to docker hub
  .github/workflows/builder.yml
Labels: ci

#565 feat: add loadning skeleton on payment detail card
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: feature

#566 fix: bugs on customer
  src/store/substrate/index.js
Labels: fix

#567 ci: fix docker entrypoint sed delimiter
  .maintain/docker/entrypoint.sh
Labels: ci

#568 fix: change variable region to state
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
Labels: fix, bug

#569 feat: add function formatReference to strin-format file
  src/common/lib/notification.js
  src/common/lib/string-format.js
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/index.vue
Labels: refactor

#570 feat: add menstrual subscription and payment page
  src/assets/menstrual-calendar-banner.svg
  src/assets/menstrual-calendar-brosure.svg
  src/assets/near-logo.svg
  src/assets/tether-logo.svg
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: feature

#573 ci: improvement
  .dockerignore
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/analyzer.yml
  .github/workflows/builder.yaml
  .github/workflows/builder.yml
  .github/workflows/deployer.yaml
  .github/workflows/deployer.yml
  .github/workflows/dev-tmp.yml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/releaser.yaml
  .github/workflows/tester.yaml
  .github/workflows/tester.yml
  .maintain/docker/Dockerfile
  .maintain/docker/docker-compose.yml
  .maintain/docker/entrypoint.sh
  README.md
  package.json
Labels: ci

#575 ci: bump scorecard to v2
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
Labels: ci

#579 ci: fix scorecard version
  .github/workflows/analyzer.yaml
Labels: ci

#581 ci: fixed release auth workflow
  .github/workflows/releaser.yaml
Labels: ci

#582 ci: fix changelog builder credentials
  .github/workflows/releaser.yaml
Labels: ci

#583 ci: fixed docker builder
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/mlc_config.json
Labels: ci

#572 feat: fix breadcrumbs
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: feature

#571 fix: get unlisted notification
  src/common/lib/notification.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Layout.vue
Labels: fix

#580 feat: menstrual dashboard side menu (summary, mood, add cycle - ui only)
  src/assets/calendar.svg
  src/assets/drink-coffee.svg
  src/assets/emoji-angry-active.svg
  src/assets/emoji-angry-inactive.svg
  src/assets/emoji-banana-active.svg
  src/assets/emoji-banana-inactive.svg
  src/assets/emoji-craving-active.svg
  src/assets/emoji-craving-inactive.svg
  src/assets/emoji-depressed-active.svg
  src/assets/emoji-depressed-inactive.svg
  src/assets/emoji-egg-active.svg
  src/assets/emoji-egg-inactive.svg
  src/assets/emoji-exhausted-active.svg
  src/assets/emoji-exhausted-inactive.svg
  src/assets/emoji-heart-eyes-active.svg
  src/assets/emoji-heart-eyes-inactive.svg
  src/assets/emoji-hungry-active.svg
  src/assets/emoji-hungry-inactive.svg
  src/assets/emoji-peanut-active.svg
  src/assets/emoji-peanut-inactive.svg
  src/assets/emoji-sad-active.svg
  src/assets/emoji-sad-inactive.svg
  src/assets/emoji-unwell-active.svg
  src/assets/emoji-unwell-inactive.svg
  src/common/components/NavigationDrawer.vue
  src/common/constants/menstrual-symptoms-emoji.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: feature

#574 feat: select menstrual date step 1 and 2
  package-lock.json
  src/assets/calendar-circle.svg
  src/assets/fertility.svg
  src/assets/menstruation.svg
  src/assets/ovulation.svg
  src/assets/prediction.svg
  src/assets/tick-circle.svg
  src/assets/today.svg
  src/assets/triangle-down.svg
  src/common/components/Calendar.vue
  src/common/components/Day.vue
  src/common/components/DaySelectAverage.vue
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: feature

#584 feat: add USN and USDT on Wallet
  src/assets/debio-logo.svg
  src/assets/near-logo.svg
  src/assets/tether-logo.svg
  src/common/components/Navbar.vue
  src/common/lib/polkadot-provider/query/octopus-assets.js
Labels: feature

#585 ci: cleanup ssh tunneling
  .github/workflows/deployer.yaml
  .maintain/docker/entrypoint.sh
  README.md
Labels: ci

#587 fix: menstrual calendar selection vertical scroll not visible & feat: subscription setting menstrual calendar
  src/common/components/Calendar.vue
  src/common/components/Day.vue
  src/common/components/DaySelectAverage.vue
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SubscriptionSetting.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: fix, feature

#590 feat: menstrual calendar dashboard
  src/common/components/Day.vue
  src/common/constants/menstruation-moods.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/mockData.js
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#593 feat: add coming soon page and bump version to 2.1.8
  package-lock.json
  package.json
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Layout.vue
  src/views/Dashboard/maintenancePageLayout.vue
Labels: feature

#594 fix: variabel service category
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
Labels: fix
