Repository debionetwork/debio-customer-ui, pull requests merged in 2022-11, with the labels that each got.

#646 fix: route after proceed
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: fix

#647 fix: contanier service lab select
  src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
Labels: fix

#656 fix: watch wallet
  src/common/components/Navbar.vue
  src/store/substrate/index.js
Labels: fix

#657 feat: connecting menstrual calendar dashboard with substrate
  src/common/constants/menstrual-symptoms-emoji.js
  src/common/lib/polkadot-provider/command/menstrual-calendar.js
  src/common/lib/polkadot-provider/query/menstrual-calendar.js
  src/store/index.js
  src/store/menstrual-calendar.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: feature

#662 fix: bugs on payment and adjust button
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: fix

#659 feat: change mens calendar payment to DBIO
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
Labels: feature

#660 fix: balance customer page
  src/common/components/Navbar.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-detail-card.spec.js
Labels: fix, feature

#663 feat: enhance add and update menstrual calendar cycle log
  src/common/components/Calendar.vue
  src/common/components/Day.vue
  src/common/lib/api/customer/index.js
  src/common/lib/api/customer/menstrual-calendar.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: feature

#664 feat: add finalized on staking status list
  src/common/constants/status.js
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
Labels: feature

#666 fix: change link tutorial token
  src/common/components/Navbar.vue
Labels: fix

#667 feat: change etherscan to octopus explorer
  .env-template
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: feature

#670 feat: enhance request test and staking flow
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-receipt-dialog.spec.js
Labels: feature

#672 feat: diabled Subscription Setting button
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
Labels: feature

#675 fix: mens date not shown
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
Labels: fix

#678 feat: enhance mens-calendar
  src/common/components/Calendar.vue
  src/common/components/Day.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: fix, feature

#677 fix: emoji next and prev month
  src/common/components/Calendar.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectEmoji.vue
Labels: fix

#679 fix: calendar
  src/common/components/Calendar.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectEmoji.vue
Labels: fix

#680 fix: select multiple dates when update
  src/common/components/Calendar.vue
  src/common/components/Day.vue
Labels: fix

#681 fix: error on average cycle date
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: fix

#683 fix: mens cycle calculation
  src/common/components/Calendar.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
Labels: fix

#684 fix: error on select-date
  src/common/components/Calendar.vue
Labels: fix

#674 fix: PHR added can't be displayed on table list
  src/views/Dashboard/Customer/Home/Phr/index.vue
Labels: fix

#685 fix: add last period when first subscribe
  src/common/components/Calendar.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: fix

#686 fix: multiple active strokeline
  src/common/components/Calendar.vue
Labels: fix

#687 fix: error on add mens cycle log
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: fix

#613 chore(main): release 2.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
