Repository debionetwork/debio-customer-ui, pull requests merged in 2022-06, with the labels that each got.

#465 fix: typo and update polkadot provider
  package-lock.json
  package.json
  src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
  src/views/Dashboard/Customer/Home/GeneticData/Result.vue
Labels: fix

#448 refactor: enhance customer dashboard and my test
  src/common/components/Dialog/ConfirmationDialog.vue
  src/common/constants/instruction-step.js
  src/common/constants/specimen-status.js
  src/common/constants/staking-status.js
  src/common/constants/status.js
  src/common/lib/api/customer/orders.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/MyTest/dataTesting.json
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/index.vue
  tests/unit/views/Dashboard/Customer/Home/MyTest/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/order-history-detail.spec.js
Labels: fix, test, refactor

#456 feat :add loading progress when download file from pinata
  src/common/components/Dialog/UploadingDialog.vue
  src/common/lib/pinata-proxy.js
  src/store/genetic-data.js
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
Labels: fix

#464 fix: handle change on metamask
  src/common/components/Navbar.vue
  src/common/lib/metamask/index.js
Labels: fix

#467 fix: remove horizontal scrollbar on analyst detail dialog
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
Labels: fix

#459 fix: trigger pop up aw snap when api error
  src/common/lib/api/index.js
  src/common/lib/error-handler.js
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: fix

#458 fix: Checkout order id url params
  src/common/lib/pinata-proxy.js
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
Labels: fix

#469 ci: add sleuth webhook
  .github/workflows/deployer.yml
Labels: ci

#470 fix: bugs on request test
  package-lock.json
  src/common/lib/metamask/escrow.js
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/Success/PaymentSuccess.vue
Labels: fix

#475 ci: fix create draft release
  .github/workflows/builder.yml
Labels: ci

#468 refactor: update EMR details caching
  src/views/Dashboard/Customer/Home/Emr/Details.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
Labels: improvement

#471 refactor: Remove customer path
  src/common/components/Navbar.vue
  src/router/routes/customer.js
  src/router/routes/index.js
  src/views/Dashboard/Customer/Layout.vue
  tests/unit/views/Dashboard/Customer/Home/PaymentHistory/details.spec.js
Labels: refactor, improvement

#473 refactor: Remove console in production
  babel.config.js
  package-lock.json
  package.json
  src/common/lib/ipfs/crypt-worker/decrypt-worker.js
  src/common/lib/ipfs/crypt-worker/encrypt-worker-file.js
  src/common/lib/ipfs/crypt-worker/encrypt-worker.js
  src/common/lib/ipfs/ipfs-worker/ipfsWorker.js
  src/common/lib/metamask/index.js
  src/common/lib/metamask/wallet.js
  src/main.js
  src/store/ethereum/index.js
  src/store/metamask/index.js
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Layout.vue
  src/views/LandingPage/SignIn/index.vue
Labels: refactor, improvement

#474 fix: staking list and coloring on recent test
  src/common/constants/status.js
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
Labels: fix

#476 fix: EMR edit and update component with loading/skeleton
  src/common/components/NavigationDrawer.vue
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Emr/Details.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/index.vue
  src/views/Dashboard/Customer/Layout.vue
  tests/unit/views/Dashboard/Customer/Home/Emr/details.spec.js
  tests/unit/views/Dashboard/Customer/Home/PaymentHistory/details.spec.js
  tests/unit/views/Dashboard/Customer/Home/PaymentHistory/index.spec.js
Labels: fix, improvement

#462 feat: cancel order & enhance create order
  src/common/components/Dialog/CancelDialog.vue
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: fix, feature

#472 feat: add loading in dashboard dataTable
  src/views/Dashboard/Customer/Home/index.vue
Labels: feature

#485 feat: add switch network to mainet / testnet
  src/common/lib/metamask/index.js
  src/common/styles/mixins.sass
  src/views/Dashboard/Customer/Layout.vue
  src/views/LandingPage/GenerateAccount/index.vue
  src/views/LandingPage/LandingPagePopUp.vue
Labels: fix, feature

#479 fix : Req ga
  src/common/lib/price-format.js
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/ServiceCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/service-card.spec.js
  tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/stepper-status-card.spec.js
Labels: fix

#489 feat: implemented polkadot wallet extension
  .browserslistrc
  package-lock.json
  package.json
  src/assets/dot-profile.png
  src/common/lib/local-storage.js
  src/common/lib/route-guard.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
  src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PayRemainingDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Layout.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  src/views/LandingPage/index.vue
  vue.config.js
Labels: feature, refactor, improvement

#486 feat: wording on successfully set / changed password page
  src/router/routes/generateAccount.js
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/GenerateAccount/SetPassword.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
  tests/unit/views/LandingPage/GenerateAccount/registration-successful.spec.js
Labels: feature, test

#488 feat: Add file size to metadata
  src/common/lib/pinata-proxy.js
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Home/GeneticData/Add.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/TestResult.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: feature, improvement

#483 feat: add issue template for bug report
  .github/ISSUE_TEMPLATE/1.bug_report.yml
Labels: feature

#490 fix: add loading display on my test
  src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
Labels: fix

#492 fix: Notification validation
  src/common/lib/polkadot-provider/events/index.js
Labels: fix

#491 feat: get all service availble
  src/common/lib/api/customer/labs.js
  src/store/lab.js
  src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
Labels: feature

#487 fix: flow cancel order
  src/router/routes/customer.js
  src/views/Dashboard/Customer/Home/RequestTest/Canceled/OrderCanceled.vue
  src/views/Dashboard/Customer/Home/RequestTest/Canceled/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: fix, feature

#481 feat: request test flow notification
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/store/substrate/event-types.json
Labels: feature

#495 fix: enhance request test flow notification
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/common/lib/polkadot-provider/events/index.js
  src/store/substrate/event-types.json
Labels: fix

#496 fix: error pages
  src/common/lib/api/index.js
  src/router/routes/customer.js
Labels: fix

#498 fix: enhance request test flow notification
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/store/substrate/event-types.json
  src/store/substrate/index.js
Labels: fix

#500 style: adjust primary color
  src/common/plugins/vuetify.js
  src/views/LandingPage/LandingPagePopUp.vue
Labels: fix

#499 feat: ada logic to show error pop up before upload file
  src/common/components/Navbar.vue
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: fix, feature

#501 fix: notification on request GA
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/common/lib/polkadot-provider/events/handlers/lab.js
  src/common/lib/polkadot-provider/events/index.js
  src/store/substrate/event-types.json
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
  src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
Labels: fix, bug
