Repository debionetwork/debio-customer-ui, pull requests merged in 2022-01, with the labels that each got.

#218 feat: mixpanel and sentry analytics.
  package-lock.json
  package.json
  src/common/lib/api/index.js
  src/main.js
Labels: enhancement

#186 fix: fix download sample result
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: bug

#225 [DBIO-1503] fix: list of staking service not show in stake service tab
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: bug

#220 [DBIO-1315] feat: adapt error message to pages
  src/common/constants/error-messages.js
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
  src/views/LandingPage/GenerateAccount/SetPassword.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
  src/views/LandingPage/SignIn/InputMnemonic.vue
  src/views/LandingPage/SignIn/index.vue
Labels: enhancement, refactor

#222 ci: improve resources requests of deployments
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#223 [DBIO-1468] tests: unit testing and update some logic on avatar component.
  src/common/components/Avatar/index.vue
  tests/unit/common/components/avatar.spec.js
Labels: tests

#229 [DBIO-1475] tests: modal unit testing.
  src/common/components/Modal/index.vue
  tests/unit/common/components/modal.spec.js
Labels: tests

#230 [DBIO-1456] feat: forgot password
  src/views/Dashboard/Customer/Layout.vue
Labels: tests

#228 docs: pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#221 fix: customer notifications
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/store/substrate/event-types.json
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: bug

#224 [DBIO-1451] refactor: restructure metamask/contract.json to env
  src/common/lib/metamask/escrow.js
  src/common/lib/metamask/service-request.js
  src/common/lib/metamask/wallet.js
  src/store/ethereum/contracts/contract.json
  src/store/ethereum/contracts/contract_ropsten.json
  src/store/ethereum/contracts/index.js
  src/store/metamask/contracts/abi/ERC20.json
  src/store/metamask/contracts/abi/ERC20Basic.json
  src/store/metamask/contracts/abi/EscrowFactory.json
  src/store/metamask/contracts/abi/ServiceRequest.json
  src/store/metamask/contracts/abi/SimpleEscrow.json
  src/store/metamask/contracts/abi/SingleEscrow.json
  src/store/metamask/contracts/contract.json
  src/store/metamask/contracts/index.js
Labels: refactor

#226 [DBIO-1468] test: unit testing and fix dropdown
  jest.config.js
  src/common/components/Dropdown/index.vue
  tests/unit/common/components/dropdown.spec.js
Labels: tests

#227 [DBIO-1461] test: unit testing banner
  src/common/components/Banner/index.vue
  tests/unit/common/components/banner.spec.js
Labels: tests

#231 [DBIO-1463] tests: unit testing component breadcrumbs
  src/common/components/Breadcrumbs/index.vue
  tests/unit/common/components/bradcrumbs.spec.js
  tests/unit/common/components/walletBinding.spec.js
Labels: tests

#232 [DBIO-1476] tests: rating unit testing
  src/common/components/Rating/index.vue
  src/common/icons/alertTriangle.js
  src/common/icons/index.js
  src/common/lib/api/index.js
  src/common/lib/polkadot-provider/command/electronic-medical-record.js
  src/router/routes/index.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
  tests/unit/common/components/rating.spec.js
Labels: tests

#233 [DBIO-1451] fix: restructure contract json to env
  src/common/lib/metamask/escrow.js
  src/store/ethereum/contracts/index.js
Labels: bug

#235 [DBIO-1467] Unit Testing Component Dialog
  src/assets/alert-circle-primary.png
  src/common/components/Dialog/AlertDialog.vue
  src/common/components/Dialog/ErrorDialog.vue
  src/common/components/Dialog/index.vue
  src/common/styles/mixins.sass
  src/views/Dashboard/Customer/Home/MyTest/ConfirmationDialog.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  tests/unit/common/components/dialog/alert-dialog.spec.js
  tests/unit/common/components/dialog/dialog.spec.js
  tests/unit/common/components/dialog/error-dialog.spec.js
Labels: tests

#236 [DBIO-1451] Refactor: remove unused ethereum contracts
  src/store/ethereum/contracts/abi/Account.json
  src/store/ethereum/contracts/abi/Degenics.json
  src/store/ethereum/contracts/abi/DegenicsLog.json
  src/store/ethereum/contracts/abi/EscrowFactory.json
  src/store/ethereum/contracts/abi/EternalStorage.json
  src/store/ethereum/contracts/abi/Lab.json
  src/store/ethereum/contracts/abi/Location.json
  src/store/ethereum/contracts/abi/Specimen.json
  src/store/ethereum/contracts/abi/SpecimenTracking.json
  src/store/ethereum/contracts/index.js
  src/store/ethereum/index.js
Labels: refactor

#237 [DBIO-1477] Tests: Unit testing component stepper
  tests/unit/common/components/stepper.spec.js
Labels: tests

#238 [DBIO-1478] Tests: Unit testing component textarea
  tests/unit/common/components/textarea.spec.js
Labels: tests

#240 Add new env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#234 fix: minor wording.
  src/common/components/Navbar.vue
  src/views/Dashboard/Customer/Home/Emr/index.vue
Labels: bug

#239 fix: notifications not showing
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/store/substrate/event-types.json
Labels: bug

#241 [DBIO-1464] Unit Testing Component Button
  tests/unit/common/components/button.spec.js
Labels: tests

#242 [DBIO-1515] - Adjust checkout to proceed payment dialog and page
  src/views/Dashboard/Customer/Home/RequestTest/PayRemainingDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: enhancement, refactor

#244 [DBIO-1209] fix: fix typo publickey
  package-lock.json
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: bug

#248 add new env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#250 [DBIO-1621] Adjust API Endpoints
  src/common/lib/api/labs.js
  src/common/lib/api/orders.js
Labels: refactor

#253 [DBIO-781] fix: remove border on navigation drawer
  src/common/components/NavigationDrawer.vue
Labels: bug, enhancement

#243 fix: Maintenance page handler
  src/common/lib/api/index.js
  src/common/lib/polkadot-provider/events/handlers/customer.js
  src/store/substrate/event-types.json
  src/views/Dashboard/Customer/maintenancePageLayout.vue
Labels: bug, enhancement

#252 [DBIO-1325] Enhance customer select service
  src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: enhancement, refactor

#249 [DBIO-1316] feat: adapt page to apply error message file
  src/common/constants/error-messages.js
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/deprecated/Upload.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
  src/views/LandingPage/SignIn/index.vue
Labels: enhancement, refactor

#254 [DBIO-1618] Handle Metamask not Installed
  src/common/components/Navbar.vue
  src/common/components/WalletBinding.vue
  src/common/lib/metamask/index.js
Labels: feature

#246 [DBIO-1470] Tests: unit testing for Icon component
  tests/unit/common/components/icon.spec.js
Labels: tests

#257 [DBIO-1556] feat: loading screen.
  src/App.vue
  src/common/icons/heartBeat.js
  src/common/icons/index.js
  src/router/index.js
  src/views/LoadingScreen.vue
  src/views/NotFound.vue
Labels: feature, improvement

#260 Fix: fix staking list table
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: fix

#261 [DBIO-1576] tests: emr dashboard unit test.
  tests/unit/views/Dashboard/Customer/Home/Emr/index.spec.js
  tests/unit/workerMock.js
Labels: tests

#262 [DBIO-1573] Refactor: Discard component Icons
  src/common/components/icons/IconBase.vue
  src/common/components/icons/SkinIcon.vue
Labels: invalid, refactor

#264 Fix: fix select service validation
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
Labels: fix

#251 [DBIO-1617 & DBIO-1646] ci: unit tests in pipeline.
  .github/workflows/pull-request.yml
  jest.config.js
  src/common/plugins/vuetify.js
  src/views/Dashboard/Customer/Home/index.vue
  tests/unit/@polkadot-api.mock.js
  tests/unit/@polkadot-keyring.mock.js
  tests/unit/@polkadot-ui-keyring.mock.js
  tests/unit/common/components/dialog/alert-dialog.spec.js
  tests/unit/common/components/dialog/dialog.spec.js
  tests/unit/common/components/dialog/error-dialog.spec.js
  tests/unit/common/components/textarea.spec.js
  tests/unit/mock.js
  tests/unit/views/Dashboard/Customer/Home/Emr/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/index.spec.js
  tests/unit/views/Dashboard/Customer/index.spec.js
  tests/unit/worker.mock.js
Labels: CI, tests

#267 [DBIO-1561] fix: Update fix english alphabet
  src/views/Dashboard/Customer/Home/Emr/Create.vue
  src/views/Dashboard/Customer/Home/Emr/Edit.vue
Labels: fix

#258 [DBIO-1373] fix: unstaking button
  src/common/lib/polkadot-provider/command/service-request.js
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  tests/unit/views/Dashboard/Customer/Home/index.spec.js
Labels: fix

#270 [DBIO-1656] CI : using environments for deployment
  .env-example
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/main.yml
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/rcb_config.json
  .github/workflows/release.yml
  .github/workflows/tester.yml
  .maintain/docker/build-image.sh
  .maintain/docker/create-network.sh
  .maintain/docker/docker-compose.yml
  .maintain/docker/start-docker-compose.sh
  .maintain/docker/stop-docker-compose.sh
  .maintain/kubernetes/.helmignore
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/hpa.yaml
  .maintain/kubernetes/templates/ingress.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/tests/test-connection.yaml
  .maintain/kubernetes/values.yaml
  README.md
Labels: ci

#272 [DBIO-1656] ci: fix deployments conditional
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  README.md
Labels: ci

#263 [DBIO-1575] tests: Add basic unit testing
  tests/unit/views/Dashboard/Customer/Home/databounty.spec.js
Labels: tests

#269 [DBIO-1569] fix: enhance staking process
  src/views/Dashboard/Customer/Home/RequestTest/PayRemainingDialog.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: fix

#273 [DBIO-1520] fix: password validation
  src/common/constants/categories.js
  src/store/auth.js
  src/views/LandingPage/GenerateAccount/SetPassword.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: fix

#276 [DBIO-1583] tests: test success page
  src/views/Dashboard/Customer/Home/RequestTest/Success/PaymentSuccess.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/Success/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/Success/payment-success.spec.js
Labels: tests

#277 [DBIO-1578] tests: request test
  tests/unit/views/Dashboard/Customer/Home/RequestTest/index.spec.js
Labels: tests

#278 [DBIO-1580] tests: test-select-service
  jest.config.js
  src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/index.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/select-service.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/agreement-dialog.spec.js
  tests/unit/views/Dashboard/Customer/Home/RequestTest/no-lab.spec.js
Labels: tests
