Repository debionetwork/debio-customer-ui, pull requests merged in 2022-08, with the labels that each got.

#535 fix: inactive loading payment history if data empty
  src/views/Dashboard/Customer/Home/index.vue
Labels: fix

#541 chore: bump version to 2.1.6
  package-lock.json
  package.json
Labels: feature

#531 refactor: Update dashboard ui
  package.json
  src/common/components/Navbar.vue
  src/views/Dashboard/Customer/Home/index.vue
Labels: refactor

#539 fix: fix loading and proceed request
  src/common/components/Dialog/LoadingDialog.vue
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/MyTest/index.vue
Labels: fix

#540 feat: Watch URL params from notification
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: improvement

#543 chore: revise env-example
  .env-example
Labels: feature

#544 fix: validation for 0 amount on staking agreement dialog
  src/common/constants/error-messages.js
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
Labels: fix

#547 fix: GA orders not loaded
  src/views/Dashboard/Customer/Home/index.vue
Labels: fix

#546 feat: add clear account when sign out and change password
  src/common/components/Navbar.vue
  src/views/Dashboard/Customer/Layout.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: feature

#548 fix: bugs on get lastorder
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: bug

#549 fix: clear account and update version 2.1.7
  package-lock.json
  package.json
  src/common/components/Navbar.vue
  src/views/Dashboard/Customer/Layout.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: fix

#545 fix: insufficient popup when amoun > balance
  src/common/lib/error-handler.js
  src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
Labels: fix

#550 fix: several issues
  src/views/Dashboard/Customer/Home/index.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: refactor, improvement

#551 fix: remaining DBIO amount on sataking dialog
  src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
Labels: fix, bug

#554 feat: revamp banner
  src/views/Dashboard/Customer/Home/MyTest/index.vue
  src/views/Dashboard/Customer/Home/Phr/index.vue
Labels: feature

#555 fix: service_flow on createOrder
  src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
Labels: fix
