Repository debionetwork/debio-customer-ui, pull requests merged in 2023-02, with the labels that each got.

#778 fix: popup dashboard
  src/views/LandingPage/GenerateAccount/SetPassword.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
  src/views/LandingPage/SignIn/InputMnemonic.vue
Labels: fix

#779 feat: enhance view for mobile access
  src/views/NoAccessMobile.vue
Labels: feature

#780 fix : fix popup dashboard
  src/views/Dashboard/Customer/Layout.vue
Labels: fix

#785 fix: enhance mobile view
  src/App.vue
  src/common/lib/api/customer/myriad.js
  src/views/NoAccessMobile.vue
Labels: fix

#789 feat: enhance menstrual subscription
  src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: fix, feature

#793 remove: registerVisibilityTimeline
  src/common/lib/api/customer/myriad.js
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
Labels: fix

#796 feat: add menstrual subscription payment detail
  src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
Labels: fix, feature

#797 feat: fix mens calendar
  src/common/components/Day.vue
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
Labels: fix

#798 fix: change field geneticDataIds to emrDataIds
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
Labels: fix

#802 feat: add download, decrypt and upload phr files
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
Labels: feature

#806 fix: format post to myriad
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
Labels: fix

#807 fix: upload file type
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
Labels: fix

#809 fix: description on second opinion
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
Labels: fix

#815 fix: handle nonce
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
Labels: fix

#816 chore(main): release 2.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
