Repository debionetwork/debio-customer-ui, pull requests merged in 2023-01, with the labels that each got.

#740 feat: add connection to myriad
  .env-template
  .maintain/docker/entrypoint.sh
  package-lock.json
  package.json
  src/assets/debio-to-myriad.svg
  src/common/lib/api/customer/index.js
  src/common/lib/api/customer/myriad.js
  src/common/lib/username-generator.js
  src/router/routes/customer.js
  src/store/index.js
  src/store/second-opinion.js
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/Description.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/GrantAccessPHR.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/index.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: fix, feature

#754 fix: adjustment layout
  src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
Labels: fix

#756 fix: layout card detail service
  src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
  src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
  src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
  tests/unit/views/Dashboard/Customer/Home/RequestTest/lab-detail-card.spec.js
Labels: fix

#745 feat: add create myriad post
  .env-template
  .maintain/docker/entrypoint.sh
  src/common/lib/api/customer/myriad.js
  src/common/lib/polkadot-provider/command/second-opinion.js
  src/store/second-opinion.js
  src/store/substrate/index.js
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/GrantAccessPHR.vue
Labels: fix

#757 feat: select emoji on menstrual calendar updates
  src/assets/emoji-hungry-active.svg
  src/assets/emoji-hungry-inactive.svg
  src/common/constants/menstrual-symptoms-emoji.js
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectEmoji.vue
Labels: feature

#763 fix: fix and adjust myriad api connection
  src/common/lib/api/customer/myriad.js
  src/common/lib/polkadot-provider/command/second-opinion.js
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
Labels: fix, feature

#767 fix: error register and auth before create post
  src/common/lib/api/customer/myriad.js
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
Labels: fix

#768 feat: connect requested opinion table to substrate
  src/common/lib/polkadot-provider/query/opinion-requestor.js
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/dummyRequestedOpinionList.json
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
Labels: feature

#774 fix: change redirect link
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: feature

#776 fix: link
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
  src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
  src/views/Dashboard/Customer/Layout.vue
Labels: fix

#777 feat: popup user
  src/assets/doctor_dashboard_modal.svg
  src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
  src/views/Dashboard/Customer/Home/index.vue
  src/views/Dashboard/Customer/Layout.vue
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/GenerateAccount/SetPassword.vue
Labels: fix, feature
